<a href="https://colab.research.google.com/github/ryujaemin2011/colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#넘파이 임포트
import numpy as np

#넘파이 배열을 만들기
arr = np.array([1, 3, 5, 7])

#배열 프린트
print('넘파이 배열: {}'.format(arr))

#배열 형태 프린트
print('배열 형태: {}'.format(arr.shape))

#배열 데이터 타입 출력
print('데이터 타입: {}'.format(type(arr)))

#요소의 데이터 타입 출력
print('배열 요소의 데이터 타입: {}'.format(arr.dtype))

#2차원 배열
arr = np.array([[1,3,5,7], [1,2,3,4]])

#배열 출력
print('넘파이 배열: {}'.format(arr))

#형태 출력
print('배열 형태: {}'.format(arr.shape))

#요솟값 0인 3행 3열 넘파이 배열
arr = np.zeros((3, 3))

#배열 출력
print('넘파이 배열: {}'.format(arr))

#요솟값 1인 2행 4열 넘파이 배열
arr = np.ones((2, 4))

#출력
print('넘파이 배열: {}'.format(arr))

#0~1사이 무작위 값 2행 4열 배열
arr = np.random.rand(2, 4)

#출력
print('넘파이 배열: {}'.format(arr))

#5이상 10미만 정수 2행 4열
arr = np.random.randint(5, 10, size=(2, 4))

#출력
print('넘파이 배열: {}'.format(arr))

#일정간격 정숫값 배열
arr1 = np.arange(1, 10, 1)

#출력
print(arr1)

#일정간격 실수배열
arr2 = np.arange(0.1, 1, 0.1)

#출력
print(arr2)

#파이썬 리스트
pylist = [1, 2, 3, 4]

#넘파이 배열
nparr = np.array([1, 2, 3, 4])

#곱셈 비교
print(pylist*2)
print(nparr*2)

arr = np.array([1, 2, 3, 4])
arrmask = arr > 2
arrfiltered = arr[arrmask]
print(arrmask)
print(arrfiltered)

넘파이 배열: [1 3 5 7]
배열 형태: (4,)
데이터 타입: <class 'numpy.ndarray'>
배열 요소의 데이터 타입: int64
넘파이 배열: [[1 3 5 7]
 [1 2 3 4]]
배열 형태: (2, 4)
넘파이 배열: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
넘파이 배열: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
넘파이 배열: [[0.2610737  0.12161397 0.08743209 0.80276077]
 [0.07618194 0.89398814 0.89910078 0.18355778]]
넘파이 배열: [[6 8 7 9]
 [9 9 6 9]]
[1 2 3 4 5 6 7 8 9]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
[False False  True  True]
[3 4]
